name: 'Setup Cloudflare WARP'
description:
  'Sets up the Cloudflare WARP client in your GitHub Actions workflow'
author: 'oHTGo'

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js

inputs:
  organization:
    description: 'The name of your Zero Trust organization'
    required: true
  auth-client-id:
    description: 'The service token client id'
    required: true
  auth-client-secret:
    description: 'The service token client secret'
    required: true
  version:
    description: 'The version of the WARP client to install'
    required: false
  retry-limit:
    description: 'The number of times to retry the WARP setup'
    required: false
    default: 5
