name: 'Setup Cloudflare WARP'
description:
  'Sets up the Cloudflare Warp client in your GitHub Actions workflow'
author: 'oHTGo'

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js

