name: Lint codebase

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install dependencies
        id: install
        run: yarn install --frozen-lockfile

      - name: Lint codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: master
          FILTER_REGEX_EXCLUDE: dist/**/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPESCRIPT_DEFAULT_STYLE: prettier
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          MARKDOWN_CONFIG_FILE: .markdown-lint.yml
          YAML_CONFIG_FILE: .yaml-lint.yml
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
